FROM surnet/alpine-wkhtmltopdf:3.20.2-0.12.6-small AS wkhtmltopdf

FROM ruby:3.1.4-alpine AS builder

ENV INSTALL_PATH=/usr/src/app/ \
    RAILS_ENV=production \
    NODE_ENV=production \
    BUNDLE_WITHOUT='development:test:mysql:aws:sandbox:ci:wkhtmltopdf' \
    # Dummy values to enable `rake assets:precompile` without a real db
    DATABASE_URL=nulldb://nohost \
    SECRET_KEY_BASE=foo

# - build-base && musl-dev: required for compiling native extensions
# - postgresql-dev: required to compile pg gem
# - shared-mime-info:: required to compile mimemagic gem
# - tzdata: required to compile tzinfo gem
RUN apk add --no-cache \
    build-base musl-dev postgresql-dev git nodejs yarn shared-mime-info tzdata

WORKDIR $INSTALL_PATH

# For Bundler caching
COPY Gemfile* $INSTALL_PATH
RUN gem install bundler -v "$(tail -1 Gemfile.lock | tr -d " ")" && \
    bundle config set --local frozen 'true' && \
    # `deployment` flag installs gems to `vendor/bundle` directory
    # https://bundler.io/guides/deploying.html#deploying-your-application
    bundle config set --local deployment 'true' && \
    bundle install --jobs=3 --retry=3

# For Yarn caching
COPY package.json yarn.lock $INSTALL_PATH
RUN yarn install --prod --frozen-lockfile --check-files

COPY . $INSTALL_PATH

# Precompile assets within builder stage
RUN bundle exec rake assets:precompile

FROM ruby:3.1.4-alpine AS production

ENV INSTALL_PATH=/usr/src/app \
    # Needed for gettext gem
    LANG=en_CA.UTF-8 \
    LC_ALL=en_CA.UTF-8

# - postgresql-client: Required for pg gem to connect to PostgreSQL
# - curl: Required for healthcheck
RUN apk add --no-cache \
    postgresql-client curl

WORKDIR $INSTALL_PATH

# Copy files from wkhtmltopdf and builder stages
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf
COPY --from=wkhtmltopdf /usr/lib/ /usr/lib/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /usr/share/mime /usr/share/mime
COPY --from=builder /usr/bin/node /usr/bin/node
COPY --from=builder $INSTALL_PATH $INSTALL_PATH

# Run container as non-root user
RUN addgroup -S dmpgroup && adduser -S dmpuser -G dmpgroup && \
    # Update ownership of files that need to be writable during production runtime
    chown -R dmpuser:dmpgroup ${INSTALL_PATH}/tmp \
    ${INSTALL_PATH}/public/ \
    # For executing translation:sync
    ${INSTALL_PATH}/config/locale \
    ${INSTALL_PATH}/config/locales

USER dmpuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD curl -f http://127.0.0.1:3000/api/v1/heartbeat || exit 1
